name = "vector-cosine-similarity"
main = "src/index.ts"
compatibility_date = "2024-11-18"

compatibility_flags = [ "nodejs_compat" ]

[vars]
OPEN_AI_API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "vector-cosine-similarity"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[[vectorize]]
binding = "VECTORIZE"
index_name = "vector-cosine-similarity"
